name: Rust

on: [push, pull_request]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo build --verbose
      - name: Release Build
        run: cargo build --verbose --release
      - name: Benchmark
        run: cargo bench --verbose
